### ISSUE TITLE
Queue may cause Out-Of-Memory

### ISSUE THREAD

**Issue by reneweb** [purposeindustries/node-logstash-client#2]
Hello everyone,

the queue that is used to queue messages when there is no connection to logstash should be capped / cleared at some point (https://github.com/purposeindustries/node-logstash-client/blob/master/lib/transports/transport.js#L10). Currently it can grow indefinetly (if the logstash connection is never established); eventually filling up all the heap space of node and causing it to crash.

**Comment by oroce** [comment]
hey, thanks for reporting this.

indeed we've never faced this yet, it can happen.

what solution is in your mind?
- throwing error when reaching n number of messages
- fixed length queue which removes the oldest items if it is filled up (LRU)
- fixed length queue which removes the newest items if it is filled up (MRU)

**Comment by reneweb** [comment]
I would go for a fixed length queue, instead of throwing an error. There can be an option, smth like max-queue-size to pass the size of it when creating a logstash instance and if not provided it can still be unlimited in size. I think I usually care more about the most recent logs then the old ones, so I'd probably go for an LRU based queue.

**Comment by adriancbo** [comment]
`node --max_old_space_size=8192 .` works for me.

**Comment by oroce** [comment]
i'm with @reneweb, actually I had something similar in my mind.

@reneweb would you open a pull request for this?

**Comment by reneweb** [comment]
@adriancbo Good that it works for you, but I don't think that it is justified to ask for such a huge heap size just to queue up messages for logstash. Furthermore, it is still possible to run out of memory, even though much more unlikely.

@oroce Will try to raise a pr for this soon.
