### ISSUE TITLE
Add new line to TCP's socket.write

### ISSUE THREAD

**Issue by oroce** [purposeindustries/node-logstash-client#3]
`socket.write(message)` should be `socket.write(message + '\n')`.

I saw @hexsprite and @LennardWesterveld fixed this, would you open a pull request for this?

**Comment by LennardWesterveld** [comment]
https://github.com/purposeindustries/node-logstash-client/pull/4/files

**Comment by oroce** [comment]
@LennardWesterveld  awesome thanks.
